# 1과목

## Numpy Library 활용 (병합)

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[5,6,7],[8,9,10]])
c = np.array([[11,12,13],[14,15,16]])

print("---concatenate---") # => 결과 2차원
con2 = np.concatenate((b,c)); print(con2,"\n")
con4 = np.concatenate((b,c), axis=1); print(con4,"\n")

print("---stack---") # => 결과 3차원
stack1 = np.stack((b,c)); print(stack1,"\n")
stack2 = np.stack((b,c), axis=1); print(stack2,"\n")

print("---append---") # => 결과 1 or 2차원
appd1 = np.append(b,c); print(appd1,"\n")
appd3 = np.append(b,c, axis=1); print(appd3,"\n")

print("---split---")
spt1 = np.split(appd3, 2); print(spt1,"\n") # 2구간으로 나눔.
spt2 = np.split(appd3, 2, axis=1); print(spt2,"\n")


---concatenate---
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]] 

[[ 5  6  7 11 12 13]
 [ 8  9 10 14 15 16]] 

---stack---
[[[ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]]] 

[[[ 5  6  7]
  [11 12 13]]

 [[ 8  9 10]
  [14 15 16]]] 

---append---
[ 5  6  7  8  9 10 11 12 13 14 15 16] 

[[ 5  6  7 11 12 13]
 [ 8  9 10 14 15 16]] 

---split---
[array([[ 5,  6,  7, 11, 12, 13]]), array([[ 8,  9, 10, 14, 15, 16]])] 

[array([[ 5,  6,  7],
       [ 8,  9, 10]]), array([[11, 12, 13],
       [14, 15, 16]])] 



## 구조적 프로그래밍

In [2]:
# 보통 함수
def getArea(a,b):
	area = a*b/2
	return area
print(getArea(5,10))

# lambda 사용
lam = lambda a,b : a*b/2
print(lam(5,10))

# lambda 사용 (값 지정)
lam1 = (lambda a,b : a*b/2)(5,10)
print(lam1)

25.0
25.0
25.0


### lambda (map, filter)

In [3]:
print(list(map(lambda a,b : a*b/2, [5,6,7],[10,11,12])))

x = [1,2,3,4,5,6,7,8,9,10]
y = list(filter(lambda t : t>5 and t<10, x))
# y2 = list(filter(lambda t : t>5 and t<10)) #안됨. ,x 있어야함.
print(y,"\n")

z1 = lambda t : t*2 if t>6 else 10*t
print(list(map(z1,x)),"\n")

z2 = lambda t : t*2 if t>9 else t*4 if t<6 else 100*t # 앞 if-else가 먼저. else일때 다음 if문 봄.
print(list(map(z2,x)))

[25.0, 33.0, 42.0]
[6, 7, 8, 9] 

[10, 20, 30, 40, 50, 60, 14, 16, 18, 20] 

[4, 8, 12, 16, 20, 600, 700, 800, 900, 20]


### pipe 함수 : 함수 내에 함수를 연속적으로 적용.

In [4]:
d = list(range(1,11,1)); print(d)
x = pd.DataFrame(d, columns=['number'])

lam1 = lambda t : t**2
y = x.pipe(lam1); print(y)

lam2 = lambda t : np.sqrt(t)
z = x.pipe(lam1).pipe(lam2)
print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


NameError: name 'pd' is not defined

# 2과목

In [ ]:
data = pd.DataFrame({'학번':['1','2','3'],
                     '성명':['김민지','민지','감자'],
                     '나이':[20,21,22]})

df = data.set_index('학번')

# 행 방향 순회 : iterrows()
for idx, row in df.iterrows():
    print(idx, row,end=' ')
    print(row['성명'])

1 성명    김민지
나이     20
Name: 1, dtype: object 김민지
2 성명    민지
나이    21
Name: 2, dtype: object 민지
3 성명    감자
나이    22
Name: 3, dtype: object 감자


In [ ]:
# 행(tuple)별 순회 : itertuples()
for item in df.itertuples():
    for i in range(len(item)):
        print(item[i])

1
김민지
20
2
민지
21
3
감자
22


# 3과목

## 1. 상관관계 분석

## 2. 회귀분석

## 3. 로지스틱 회귀분석

In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

iris = load_iris()
irisdata = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                        columns = iris['feature_names']+['target'])
irisdata['target'] = irisdata['target'].map({0:'setosa', 1:'versicolor', 2:'virginica'})
print(irisdata.columns[:-1])
features = irisdata[irisdata.columns[:-1]]
labels = irisdata['target']

scaler = StandardScaler()
scaler.fit(features) # 독립변수 값 계산
x = scaler.transform(features) # 독립변수 값 변환(x)

model = LogisticRegression(C=20, max_iter=1000)
model.fit(x,labels)

print(model.score(x, labels)*100)
print(model.classes_)
print(model.coef_.shape)
print(model.coef_) # 각 features의 계수
print(model.intercept_) # 각 features의 절편
deci = model.decision_function(x[:5]) # 수치로 모델이 얼만큼 확신하는지 알 수 있음.
print()
print(x[:5])
print(np.round(deci,2))
print(labels[:5]," => ",model.predict(x[:5]))

prob = model.predict_proba(x[:5])
print(np.round(prob,3))



Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
98.0
['setosa' 'versicolor' 'virginica']
(3, 4)
[[-2.01795678  2.16894971 -4.16544443 -3.91927077]
 [ 1.57386885 -0.37329405 -1.97977627 -1.6778015 ]
 [ 0.44408793 -1.79565566  6.1452207   5.59707228]]
[ 0.25538716  4.80583194 -5.0612191 ]

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
[[ 15.02   7.87 -22.89]
 [ 13.01   7.92 -20.93]
 [ 14.74   7.48 -22.21]
 [ 14.01   7.15 -21.16]
 [ 15.77   7.59 -23.36]]
0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: target, dtype: object  =>  ['setosa' 'setosa' 'setosa' 'setosa' 'setosa']
[[0.999 0.001 0.   ]
 [0.994 0.006 0.   ]
 [0.999 0.001 0.   ]
 [0.999 0.001 0.   ]
 [1.    0.    0.   ]]


## 4. 의사결정나무

## 5. 인공신경망

## 6. 서포트벡터머신

## 7. 베이지안 기법

## 8. 앙상블 기법

## 9. 군집 및 k-NN 분류 분석

## 10. 연관성 분석

# 4과목